CREATE TABLE balance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE UNIQUE , -- id пользователя
    current INT, -- текущий баланс храним в копейках
    withdraw INT -- списанные баллы так же храним в копейках
);